# ----
# Site

title: Thomas Königs Portfolio - Fullstack Web Developer in Munich
description: Learn something about Thomas König. Fullstack Web Developer in Munich!
url: http://portfolio.koenigthomas.de/

author: Thomas König mail@koenigthomas.de
social:
  name: Thomas König Portfolio
  links:
    - https://github.com/vispercept
    - https://github.com/nicewebsites
    - https://de.linkedin.com/in/thomas-könig-6414176b
    - https://www.xing.com/profile/Thomas_Koenig202
    - https://twitter.com/tmskng
google_site_verification: k_sbuaryqKZYAEH8jbSu97qCNVPhn-Gb5fLH3zq3mjI

# -----
# Build

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
