# ----
# Site

title: Thomas König Portfolio
url: http://portfolio.koenigthomas.de/

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
description: Thomas Königs portfolio website
author:
  name: Thomas König
  email: mail@koenigthomas.de
  twitter: tmskng
social:
  name: Thomas König Portfolio
  links:
    - https://github.com/vispercept

# -----
# Build

permalink: pretty

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1880
          height: 1880
  -
    scope:
      path: ""
    values:
      layout: "default"

gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_options:
